server:
  port: 9002
spring:
  application:
    name: microservice-movie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
      #defaultZone: http://localhost:8888/eureka,http://localhost:9999/eureka
  instance:
    prefer-ip-address: true

#修改Ribbon负载均衡算法
microservice-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#开启Hystrix熔断功能
feign:
  hystrix:
    enabled: true
